basePath: /
consumes:
- application/json
definitions:
  AlertCredentialResponse:
    properties:
      entity:
        type: string
        x-go-name: Entity
      pagerduty_credentials:
        type: string
        x-go-name: PagerdutyCredentials
      slack_config:
        $ref: '#/definitions/SlackConfig'
    type: object
    x-go-package: github.com/odpf/siren/docs
  Rule:
    properties:
      CreatedAt:
        format: date-time
        type: string
      UpdatedAt:
        format: date-time
        type: string
      entity:
        type: string
        x-go-name: Entity
      group_name:
        type: string
        x-go-name: GroupName
      id:
        format: uint64
        type: integer
        x-go-name: ID
      name:
        type: string
        x-go-name: Name
      namespace:
        type: string
        x-go-name: Namespace
      status:
        type: string
        x-go-name: Status
      template:
        type: string
        x-go-name: Template
      variables:
        items:
          $ref: '#/definitions/RuleVariable'
        type: array
        x-go-name: Variables
    type: object
    x-go-package: github.com/odpf/siren/domain
  RuleVariable:
    properties:
      description:
        type: string
        x-go-name: Description
      name:
        type: string
        x-go-name: Name
      type:
        type: string
        x-go-name: Type
      value:
        type: string
        x-go-name: Value
    type: object
    x-go-package: github.com/odpf/siren/domain
  SlackConfig:
    properties:
      critical:
        $ref: '#/definitions/SlackCredential'
      warning:
        $ref: '#/definitions/SlackCredential'
    type: object
    x-go-package: github.com/odpf/siren/domain
  SlackCredential:
    properties:
      channel:
        type: string
        x-go-name: Channel
      username:
        type: string
        x-go-name: Username
      webhook:
        type: string
        x-go-name: Webhook
    type: object
    x-go-package: github.com/odpf/siren/domain
  Template:
    properties:
      CreatedAt:
        format: date-time
        type: string
      UpdatedAt:
        format: date-time
        type: string
      body:
        type: string
        x-go-name: Body
      id:
        format: uint64
        type: integer
        x-go-name: ID
      name:
        type: string
        x-go-name: Name
      tags:
        items:
          type: string
        type: array
        x-go-name: Tags
      variables:
        items:
          $ref: '#/definitions/Variable'
        type: array
        x-go-name: Variables
    type: object
    x-go-package: github.com/odpf/siren/domain
  Variable:
    properties:
      default:
        type: string
        x-go-name: Default
      description:
        type: string
        x-go-name: Description
      name:
        type: string
        x-go-name: Name
      type:
        type: string
        x-go-name: Type
    type: object
    x-go-package: github.com/odpf/siren/domain
host: localhost:3000
info:
  description: Documentation of our Siren API.
  title: Siren.
  version: 1.0.0
paths:
  /alertingCredentials/teams/{teamName}:
    get:
      description: 'Get AlertCredentials API: This API helps in getting the teams
        slack and pagerduty credentials'
      operationId: getAlertCredentialRequest
      parameters:
      - description: name of the team
        in: path
        name: teamName
        required: true
        type: string
        x-go-name: TeamName
      responses:
        "200":
          description: AlertCredentialResponse
          schema:
            $ref: '#/definitions/AlertCredentialResponse'
      tags:
      - alertcredential
    put:
      description: 'Upsert AlertCredentials API: This API helps in creating or updating
        the teams slack and pagerduty credentials'
      operationId: createAlertCredentialRequest
      parameters:
      - description: Create AlertCredential request
        in: body
        name: Body
        schema:
          $ref: '#/definitions/AlertCredentialResponse'
      - description: name of the team
        in: path
        name: teamName
        required: true
        type: string
        x-go-name: TeamName
      responses:
        "200":
          description: ""
      tags:
      - alertcredential
  /ping:
    get:
      description: Ping call
      operationId: ping
      responses:
        "200":
          $ref: '#/responses/pingResponse'
      tags:
      - ping
  /rules:
    get:
      description: 'List Rules API: This API lists all the existing rules with given
        filers in query params'
      operationId: listRulesRequest
      parameters:
      - description: List Rule Request
        in: query
        name: namespace
        type: string
        x-go-name: Namespace
      - in: query
        name: entity
        type: string
        x-go-name: Entity
      - in: query
        name: group_name
        type: string
        x-go-name: GroupName
      - in: query
        name: status
        type: string
        x-go-name: Status
      - in: query
        name: template
        type: string
        x-go-name: Template
      responses:
        "200":
          $ref: '#/responses/listResponse'
      tags:
      - rules
    put:
      description: 'Upsert Rule API: This API helps in creating a new rule or update
        an existing one with unique combination of namespace, entity, group_name,
        template'
      operationId: createRuleRequest
      parameters:
      - description: Create rule request
        in: body
        name: Body
        schema:
          $ref: '#/definitions/Rule'
      responses:
        "200":
          $ref: '#/responses/rulesResponse'
      tags:
      - rules
  /templates:
    get:
      description: 'List Templates API: This API lists all the existing templates
        with given filers in query params'
      operationId: listTemplatesRequest
      parameters:
      - description: List Template Request
        in: query
        name: tag
        type: string
        x-go-name: Tag
      responses:
        "200":
          $ref: '#/responses/listResponse'
      tags:
      - templates
    put:
      description: 'Upsert Templates API: This API helps in creating or updating a
        template with unique name'
      operationId: createTemplateRequest
      parameters:
      - description: Create template request
        in: body
        name: Body
        schema:
          $ref: '#/definitions/Template'
      responses:
        "200":
          $ref: '#/responses/templatesResponse'
      tags:
      - templates
  /templates/{name}:
    delete:
      description: 'Delete Template API: This API deletes a template given the template
        name'
      operationId: deleteTemplatesRequest
      parameters:
      - description: Delete Template Request
        in: path
        name: name
        required: true
        type: string
        x-go-name: Name
      responses:
        "200":
          $ref: '#/responses/templatesResponse'
      tags:
      - templates
    get:
      description: 'Get Template API: This API gets a template given the template
        name'
      operationId: getTemplatesRequest
      parameters:
      - description: Get Template Request
        in: path
        name: name
        required: true
        type: string
        x-go-name: Name
      responses:
        "200":
          $ref: '#/responses/templatesResponse'
      tags:
      - templates
  /templates/{name}/render:
    post:
      description: 'Render Template API: This API renders the given template with
        given values'
      operationId: renderTemplatesRequest
      parameters:
      - description: Render Template Request
        in: path
        name: name
        required: true
        type: string
        x-go-name: Name
      responses:
        "200":
          $ref: '#/responses/renderTemplatesResponse'
      tags:
      - templates
produces:
- application/json
responses:
  listResponse:
    description: List templates response
    schema:
      items:
        $ref: '#/definitions/Template'
      type: array
  pingResponse:
    description: Response body for Ping.
  renderTemplatesResponse:
    description: ""
  rulesResponse:
    description: ""
    schema:
      $ref: '#/definitions/Rule'
  templatesResponse:
    description: ""
    schema:
      $ref: '#/definitions/Template'
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
